# Generated by Django 4.2.5 on 2023-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessages',
            fields=[
                ('primaryKey', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('CreateDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeMessages',
            fields=[
                ('primaryKey', models.AutoField(primary_key=True, serialize=False)),
                ('textfield', models.TextField()),
                ('timestampfield', models.DateTimeField()),
                ('datefield', models.DateTimeField()),
                ('CreateDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
