# Generated by Django 4.2.5 on 2023-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMessages',
            fields=[
                ('primaryKey', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('weekname', models.DateTimeField()),
                ('CreateDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
