# Generated by Django 4.2.5 on 2023-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_timestamp_weeklymessages_addtimestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBarStatus',
            fields=[
                ('ProgressbarPK', models.AutoField(primary_key=True, serialize=False)),
                ('ProgressbarStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
