# Generated by Django 4.2.5 on 2023-09-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    def add_initial_data(apps, schema_editor):
        ProgressBarStatus = apps.get_model('app', 'ProgressBarStatus')
        ProgressBarStatus.objects.create(ProgressbarStatus=True)  # Замените значения по вашему усмотрению



    dependencies = [
        ('app', '0005_progressbarstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressbarstatus',
            old_name='ProgressbarPK',
            new_name='ProgressbarPKey',
        ),
        migrations.RunPython(add_initial_data),
    ]
